### ISSUE TITLE
Are you doing this by hand?

### ISSUE THREAD

**Issue by linonetwo** [rimi/tw5-telmiger-plugins#1]
That would be a huge work to redone this when plugin gets update, for example now...

**Comment by rimi** [comment]
> 
> 
> That would be a huge work to redone this when plugin gets update, for example now...

yes, for now. do you have a better option (except let him do it on his own -> asked him already, but he works with html-only)?

**Comment by linonetwo** [comment]
I try do it by hand today (I want to get nodejs version of simple-search), I export the JSON, and use js to parse it, and log it, then I manually copy the log from console to actual file, maybe should use fs.writeFileSync instead.

**Comment by linonetwo** [comment]
Can you write JS?

**Comment by rimi** [comment]
I'm using JS all day in my private and work-life, but seriously? I mean, you trying to exchange something that - yes, it is triggered manually - takes me approx. 5 seconds per plugin to execute by just dropping the plugin to an empty node-tw5 and "sync" the folders to the local GIT repo; against a script that also needs to be triggered manually by importing it into telmigers tw5 and than execute it? We are talking about Plugin-Changes every 6 month or so. Even if not all the tiddlers end up in $:/plugins/telmiger/whatever-folders and -subfolders it is no big deal to distinguish them even when importing all at once (when you for instance take advantage of the bundler-plugin). Don't understand me wrong, i would highly appreciate a scripted way to automatically sync all the plugin-contents to the right subdir within my git-repo (including removing all the erased/renamed), but i never even thought about trying that because most good plugins out there are already GITed ;) I used to use telmigers stuff but not that much anymore anyway. However feel free! ;) 
But you should check in the TW5-Group if someone already solved that more elegantly than i currently do...

**Comment by rimi** [comment]
i updated simplesearch to 1.0.24 minutes ago. actually, as i didn't do it for months now, i had to remember all the steps, but it came relatively easily. the steps where as follows:

1.) start an empty node-tw5 locally
2.) open telmigers tw5 and drop the bundle-plugin into it
3.) do not reload ;) but save the now updated telmiger tw5-file locally
4.) activate "filtered bundles" in the bundles plugin
5.) set the filtered.bundle filter-property to "[[$:/plugins/telmiger/simple-search]plugintiddlers[]]"
6.) download the JSON and drop it to your local node-tw5
7.) replace the old folder-contents with the new
8.) AND yes, this IS annoying: plugin.info needs to be updated in my "process" manually by also dropping the full plugin to your node-tw5 and putting it into edit-mode => copy/paste the props manually
 9.) Commit&Done

So, ok without doing it for months it it took me 2 minutes today (and i even forgot to copy one property correctly into the plugin.info at first...) but writing this post took me longer :D

Anyway, someone elses "scripted way" to automate this more, would be cool!  ;)

**Comment by linonetwo** [comment]
I see, but after step 6, file created by nodejs have strange name, how do you modify them and place them into the correct folders?

**Comment by rimi** [comment]
that one: https://github.com/wikilabs/plugins/tree/master/wikilabs/bundler

**Comment by linonetwo** [comment]
Oh, seems you have updated all the stuff, don't need my help then.

**Comment by linonetwo** [comment]
I can help you make this a plugin library, do you need this?

**Comment by rimi** [comment]
it would make it easier. if you can make it, i would appreciate it!

**Comment by rimi** [comment]
> 
> 
> I see, but after step 6, file created by nodejs have strange name, how do you modify them and place them into the correct folders?

use https://tiddlywiki.com/static/Customising%2520Tiddler%2520File%2520Naming.html. Mine only contains

```
[is[system]removeprefix[$:/]addprefix[_system/]]
[!has[draft.of]]
```

to make it work with my directory-structure

**Comment by linonetwo** [comment]
Hi, I have prepared a PR, please see!

**Comment by linonetwo** [comment]
Actually I think that `_system` folder is extra, maybe it should be omitted, because other plugins just directly put files in the plugin folder, without this extra layer.

---

But to make our process simple, I think keep it is OK.

**Comment by rimi** [comment]
You are absolutely right, but in the past it didn't disrupt me because it is just cosmetically ;)
Anyway, if your script honors and fixes that i definitely will change the structure of the plugin!

**Comment by rimi** [comment]
> 
> 
> Hi, I have prepared a PR, please see!

nice! i'll check that out as sonn as possbile. thx
